name = "beach-bar-api"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "c28ea6353f4a578e429690ad3944c16b"

# Uncomment to deploy to a custom domain
# routes = [
#   { pattern = "api.mulletmcnasty.com", custom_domain = true }
# ]

[env.production]
name = "beach-bar-api"

[env.dev]
name = "beach-bar-api-dev"
